server:
  port: 9915
backbase:
  security:
    public:
      paths: /**

logging:
  level:
    root: INFO
    com.backbase: DEBUG
# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
     enabled: false
#Database config
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:greetingsdb;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-persistence.xml
